<script lang="ts">
import { createComponent } from '@vue/composition-api'
import Icon from 'vue-awesome/components/Icon'

const builtIn = [
  'heart'
]

// Registering custom icons
// If the svg size is too large, should be generated by icomoon first, prefer `width: 16, height: 16`
const custom = {}

builtIn.map(name => require(`vue-awesome/icons/${name}`))
Icon.register(custom)

export const iconNames = [
  ...builtIn,
  ...Object.keys(custom)
]

// @vue/component
export default createComponent({
  ...Icon,

  name: 'YcIcon',

  // More props, see https://github.com/Justineo/vue-awesome#props
  props: {
    ...Icon.props,
    name: {
      type: String,
      required: true,
      validator: (val: string) => {
        return iconNames.includes(val)
      }
    }
  }
})
</script>
